input_dir: "/data/NCBR/projects/NCBR-174/FunannotateMake/input"
result_dir: "/data/NCBR/projects/NCBR-174/FunannotateMake"
fastq_dir: "/data/NCBR/projects/NCBR-174/fastq"
repeat_file: "/data/NCBR/projects/NCBR-174/Genome-Annotation/pilon124_round3_chromosomesnumbered-families.fa"
protein_file: "/data/NCBR/projects/NCBR-174/FunannotateMake/param_files/strongyloides_stercoralis.PRJEB528.WBPS17.protein.fa"
transcript_file: "/data/NCBR/projects/NCBR-174/FunannotateMake/param_files/strongyloides_stercoralis.PRJEB528.WBPS17.mRNA_transcripts.fa"
funannotate_dir: "/data/NCBR/projects/NCBR-298"
species: "Strongyloides stercoralis"
